# Generated by Django 5.1.3 on 2024-11-24 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='api_receita.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Favorita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='api_receita.receita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='api_receita.usuario')),
            ],
            options={
                'unique_together': {('receita', 'usuario')},
            },
        ),
    ]
